name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: granting private modules access
        run: |
          git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/nrfta".insteadOf "https://github.com/nrfta"

      - name: Install Dependencies
        run: |
          go env -w GOPRIVATE=github.com/nrfta
          go mod download

      - name: Tests
        run: go test -v ./...
